name       : python-freezegun
version    : 0.3.11
release    : 1
source     :
    - https://pypi.io/packages/source/f/freezegun/freezegun-0.3.11.tar.gz : e839b43bfbe8158b4d62bb97e6313d39f3586daf48e1314fb1083d2ef17700da
license    : Apache-2.0
component  : programming.python
summary    : Let your Python tests travel through time
description: |
    FreezeGun is a library that allows your Python tests to travel through time by mocking the datetime module.
builddeps  :
    - python-coverage
    - python-dateutil
    - python-nose
    - python-mock
    - python-setuptools
rundeps    :
    - python-dateutil
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test nosetests
    %python3_test nosetests-%python3_version%
