name       : python-freezegun
version    : 1.2.2
release    : 10
source     :
    - https://files.pythonhosted.org/packages/source/f/freezegun/freezegun-1.2.2.tar.gz : cd22d1ba06941384410cd967d8a99d5ae2442f57dfafeff2fda5de8dc5c05446
license    : Apache-2.0
homepage   : https://github.com/spulec/freezegun
component  : programming.python
summary    : Let your Python tests travel through time
description: |
    FreezeGun is a library that allows your Python tests to travel through time by mocking the datetime module.
builddeps  :
    - python-coverage
    - python-dateutil
    - python-nose
    - python-mock
    - python-pytest
rundeps    :
    - python-dateutil
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -k 'not test_datetimes'
